development:
 adapter: postgresql
 encoding: utf8
 database: archo_development
 username: postgres
 password: password
 host: localhost
 pool: 2
 timeout: 5000

production:
 adapter: postgresql
 encoding: utf8
 database: archo_production
 username: postgres
 password: password
 host: localhost
 pool: 2
 timeout: 5000
